### PR TITLE
remove System.Buffers

### PR DESCRIPTION
**Pull request by SimonCropp**
is it really required?

### CODE REVIEW

**Comment by FlorianRappl** [comment]
Previously it was. Should be confirmed that it works without it.

**Comment by FlorianRappl** [comment]
I think this is required. See #963.

**Comment by SimonCropp** [comment]
weird that it still builds?

**Comment by FlorianRappl** [comment]
Depends on the target. My guess is that since System.Buffers exists only up to version 4.5.1 with the targets we have it might not be needed (anymore) and that it was actually previously be over-specified (i.e., its part of all target frameworks and we do not need the explicit reference).

**Comment by SimonCropp** [comment]
well it builds, and tests pass. so IMO we remove it

**Review by FlorianRappl — APPROVED** [review]

**Pull request merged**
