### PR TITLE
Issue #313

### PR DESCRIPTION
**Pull request by FlorianRappl**
I also looked over other uses of the ACK-flag. Seems to be alright so far.

### CODE REVIEW

**Comment by driekus77** [comment]
Hi all,

Is there any sign of releasing this fix?
Are there workarrounds where I can work with?

Thanks for any help.

Henry

**Comment by FlorianRappl** [comment]
Unfortunately, I currently have too much work to do besides AngleSharp, which is why there are still some other (unrelated) issues waiting to be completed before v0.9.6 can be released.

If you can't wait I recommend to get the repo (branch `devel`), build it, and then reference it. I am sorry that it is that inconvenient, but I'd like v0.9.6 to be complete before its being published. I hope to find the time to release v0.9.6 either this week or the next.

**Comment by driekus77** [comment]
@FlorianRappl Thanks for your quick reply.

Unfortunately I've tried tried rebuilding AngleSharp develop branch but the problem still remains. Am I missing a setting somewhere? I am using AngleSharp under the PreMailer. Tested both by compiling the Release target en referencing AngleSharp from PreMailer.

Thanks for the help.
Henry

**Comment by FlorianRappl** [comment]
What exactly is your problem? Can you provide a MWE? Potentially, there is not a problem but rather a mismatch of expectation.

**Comment by driekus77** [comment]
Hi,

My valid XHTML input:
`
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width"/>
`

Is parsed to invalid XHTML output:
`
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width">
`

Because of the self closing tags missing. I've attached a zip file with my input html example: hero.html and a PreMailer.NET output example: hero.out.html.

Again Thanks for the help.

Kind regards,
Henry

[hero.zip](https://github.com/AngleSharp/AngleSharp/files/236203/hero.zip)

**Comment by FlorianRappl** [comment]
This is (as already thought) not an issue with AngleSharp, but with the expectations you have. AngleSharp behaves like a browser (it has an HTML5 engine at its core), i.e., the input you show is parsed as usual.

The output you present is _one_ possible representation (not _the_ representation). You could implement your own serializer (given in form of an implementation of the `IMarkupFormatter` interface) to produce exactly the output you'd like to see.

So the misconception is that AngleSharp parses a string to a string. In fact it parses a string to an object model. The string you see is just _one representation_ (which happens to be the standard HTML5 way) and may be different to what you want / need.

**Comment by driekus77** [comment]
Hi @FlorianRappl,

Aha now I'm getting it. Thanks again.

I also looked at other issues concerning XHTML formatter and AngleSharp. I'm a C# developer and willing to write a XhtmlMarkupFormatter. But I have 2 questions before I dive into that:
- Would it be possible to select the new to be XHtmlMarkupFormatter depending on original DocType?
- How would you implement this XHtml formatter? As extension (inheritance) of XmlMarkupFormatter or HtmlMarkupFormatter or Standalone? Where the Standalone could cause code dupplication.

Kind regards,
Henry

**Comment by FlorianRappl** [comment]
It is possible to supply a serializer that works according to the doctype. I would go as follows:
- Start with your own implementation of `IMarkupFormatter`
- Provide a field with a child `IMarkupFormatter` (by default set to the default serializer)
- On serializing a doctype try to find a better match (otherwise fall back to the default serializer) and set the field to the new selection
- Always use the selected serializer for all the implemented methods

I would call this one `AutoSelectedMarkupFormatter` or similar. But for sure such a component would requrie the `XHtmlMarkupFormatter`.

Inheritance of the formatters is usually not encouraged. Instead, you should prefer composition. Independent of that decision - yes, the `XmlMarkupFormatter` is possibly the closest match!

Hope this helps you!

**Pull request merged**
