### PR TITLE
Add back missing NET6+ targets to AngleSharp.nuspec

### PR DESCRIPTION
**Pull request by lahma**
# Types of Changes

## Prerequisites

Please make sure you can check the following two boxes:

- [x] I have read the **CONTRIBUTING** document
- [x] My code follows the code style of this project

## Contribution Type

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue, please reference the issue id)
- [ ] New feature (non-breaking change which adds functionality, make sure to open an associated issue first)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

## Description

While there's still ongoing discussion about pros and cons for using csproj instead of nuspec file on #1189 I think it's better to fix what I broke as an intermediate solution. Bringing back explicit dependency targets without the actual dependencies.

### CODE REVIEW

**Comment by lahma** [comment]
Another food for thought, NET 7 will be obsolete next month so how long should that be supported as an explicit target.

**Review by FlorianRappl — APPROVED** [review]
Thanks for spotting this!

**Comment by FlorianRappl** [comment]
> Another food for thought, NET 7 will be obsolete next month so how long should that be supported as an explicit target.

As long as we can (i.e., as long as it does not "hurt" / limit us) - but same as with .NET 4.6.1 if we ever encounter even the slightest problem we'd remove it.

**Comment by lahma** [comment]
> > Another food for thought, NET 7 will be obsolete next month so how long should that be supported as an explicit target.
> 
> As long as we can (i.e., as long as it does not "hurt" / limit us) - but same as with .NET 4.6.1 if we ever encounter even the slightest problem we'd remove it.

Yep, I think the pain starts to hit if GH Actions runners start to drop obsolete targeting.

**Pull request merged**
