### PR TITLE
Fix 1212

### LINKED ISSUE #1212: Cookie 'Expires' Header Recognized as Local Time Instead of GMT in .NET 9
### Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [X] Are you running the latest version of AngleSharp?
- [X] Did you check the FAQs to see if that helps you?
- [X] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [X] Did you perform a search in the issues?

### Description

I am not fluent in English as I am Japanese, so I am using AI assistance to create this issue. Please forgive any mistakes in grammar or word choice. Feel free to ask for clarification if anything is unclear. Thank you for your understanding.
This problem occurs in .NET 9. NET 8, the problem does not occur in .NET 8, it is caused by changing the TargetFramework to net9.
When upgrading a project using AngleSharp from .NET 8 to .NET 9, an issue arises where cookies with an Expires attribute are misinterpreted. Specifically, the expiration date specified in GMT is incorrectly parsed as local time, leading to immediate expiration of cookies that should still be valid.

## Description

This issue occurs in the JST (GMT+9) time zone, based on the following example:

1. Access a URL that responds with the following `Set-Cookie` header:
`Set-Cookie: name=value; Expires=Mon, 30 Dec 2024 00:30:00 GMT`
Assume the current time is `Mon, 30 Dec 2024 00:30:00 GMT`, and the cookie is set to expire in 30 minutes.

2. Immediately send a request to another URL. Since the cookie has not yet expired, the Cookie header should be included in the request.

However, the `Expires` value (`Mon, 30 Dec 2024 00:30:00 GMT`) is mistakenly interpreted as local time (in this case, JST).

* The current time in JST is `Mon, 30 Dec 2024 09:00:00`
* Comparing these timestamps: `30 Dec 2024 00:30:00` < `30 Dec 2024 09:00:00`, the cookie is treated as expired.
* As a result, the `Cookie` header is not included in the request.

## Impact		
		
Due to this issue, in the JST time zone, any cookie with an expiration time of less than 9 hours is never used in requests.		
		
## Evidence		

Below is a confirmation of the issue based on packet capture:

### Cases of expiry
image

### Cases that do not expire
image

### Steps to Reproduce

```.cs
var angleConfig = Configuration.Default.WithDefaultLoader().WithDefaultCookies();
using var context = BrowsingContext.New(angleConfig);
_ = await context.OpenAsync($"http://192.168.163.1:2000/Home/Index2"); // URL to which the set-cookie is responded to.
_ = await context.OpenAsync($"http://192.168.163.1:2000/Home/Last"); // URL where the cookie set above is used for the request
```

### Expected Behavior

The `Expires` attribute in the `Set-Cookie` header should always be interpreted as a GMT timestamp, as specified by the HTTP standard.

* If the current time is before the `Expires` time, the cookie should be considered valid and included in the `Cookie` header of subsequent requests.
* This behavior should remain consistent across all time zones, including JST (GMT+9).

### Actual Behavior

The `Expires` attribute in the `Set-Cookie` header is incorrectly interpreted as local time (e.g., JST instead of GMT).

* In cases where the local time is already past the `Expires` time (even though the GMT time is still valid), the cookie is treated as expired.
* As a result, the `Cookie` header is not included in subsequent requests, even when the cookie is still valid according to GMT.

### Possible Solution / Known Workarounds

I plan to create a pull request to address this issue. However, this will be my first contribution to an open-source project, so it may take some time to complete. Thank you for your patience and understanding.

https://github.com/AngleSharp/AngleSharp/blob/5dc976bb0c4b30799e28a0ea43eff180f4259964/src/AngleSharp/Io/MemoryCookieProvider.cs#L84

In the string manipulation logic within the source code linked above, the "GMT" designation is being removed from the cookie string. If "GMT" is missing, it appears that in .NET 8, the timestamp was still interpreted as GMT. However, in .NET 9, the timestamp is interpreted as local time instead.

I believe this issue can be resolved by modifying the source code to retain the "GMT" designation, as shown below:

```.cs
var time = utc.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'", CultureInfo.InvariantCulture);
```

### PR DESCRIPTION
**Pull request by noobow34**
# Types of Changes

## Prerequisites

Please make sure you can check the following two boxes:

- [x] I have read the **CONTRIBUTING** document
- [x] My code follows the code style of this project

## Contribution Type

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [x] Bug fix (non-breaking change which fixes an issue, please reference the issue id)
- [ ] New feature (non-breaking change which adds functionality, make sure to open an associated issue first)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

## Description

I have made the fixes as described in #1212. During testing, I added .NET 9.0 to the TargetFramework, but this change is not included in the commit.

### CODE REVIEW

**Comment by noobow34** [comment]
In Japan, the new year is just around the corner, but before 2024 ends, I was able to send my first pull request to an OSS project. Wishing you a Happy New Year!

**Comment by FlorianRappl** [comment]
> In Japan, the new year is just around the corner, but before 2024 ends, I was able to send my first pull request to an OSS project. Wishing you a Happy New Year!

Happy new year and thanks for your contribution!

**Review by FlorianRappl — APPROVED** [review]
LGTM!

**Comment by noobow34** [comment]
Thank you for the review. I’m very happy to have been able to contribute to OSS for the first time!

**Pull request merged**
