### PR TITLE
Fix memory leak caused by long-duration intervals or timeouts

### PR DESCRIPTION
**Pull request by ArcanoxDragon**
Fixes AngleSharp/AngleSharp.Scripting#41

### CODE REVIEW

**Comment by FlorianRappl** [comment]
Thanks for the PR! 👍 
I will look into changing the build.ps1 / Cake for using the csproj again. Will be merged asap then!

🍻

**Comment by ArcanoxDragon** [comment]
I'm actually fiddling around with Cake right now trying to get it to build. It loads the new .NET Core `.csproj` file just fine, but it's looking for the source files in `C:\` instead of the project directory. It may be a local configuration issue for me...I'm still digging around.

**Comment by ArcanoxDragon** [comment]
Technically I believe this can actually be merged in before the project files are migrated, but it'd be good to get those migrated so a prerelease version can be published to NuGet.

**Comment by FlorianRappl** [comment]
Agreed!

**Comment by ArcanoxDragon** [comment]
I just pushed to #578 again...I still can't get the project to build in Cake on my workstation but it builds on my tablet with a fresh clone of my `csproj` branch, so it must be a machine issue.

**Comment by FlorianRappl** [comment]
Looks great - now I will need to look into #566.

**Comment by ArcanoxDragon** [comment]
@FlorianRappl that should be fixed with the migration to `.csproj`, which involved removing the .NET Portable frameworks (as they are effectively deprecated... .NET Core has pretty much replaced portable frameworks).

**Comment by FlorianRappl** [comment]
Hm if it is solved then why is the build failing on AppVeyor? Am I missing something?

**Comment by ArcanoxDragon** [comment]
I changed the project format in a different PR/branch, so this PR is still trying to build with project.json. The code should compile fine in VS but I've noticed all the recent PRs have been failing in AppVeyor because of the .NET Core format change

**Comment by FlorianRappl** [comment]
Yeah sorry I was confused about #578 (two PRs). The last two comments from me actually referred to #578.

**Comment by FlorianRappl** [comment]
This PR of course looks great!
Merged 🥇 !

**Pull request merged**
