### PR TITLE
Update project.json to solve issue-534

### PR DESCRIPTION
**Pull request by gabriele-tomassetti**
Add System.Text.Encoding.CodePages to solve the issue 534, but to do that it also need to upgrade to netstandard1.3.
This is something that need to be checked.

### CODE REVIEW

**Comment by gabriele-tomassetti** [comment]
Sorry, I forgot to mention the **really important fact** that this doesn't actually solves the issue (ie, adding Encoding.RegisterProvider). Before doing that I am waiting to know if it's ok to upgrade to netstandard1.3.

**Comment by FlorianRappl** [comment]
Yep, let's discuss this in #534 in detail. No need to rush into it. Thanks for noticing!

**Comment by 304NotModified** [comment]
I think the best solution here is to make a specialized build for .NET standard 1 and 1.3 - then the issues could be solved in .NET standard 1.3

**Comment by FlorianRappl** [comment]
Closing due to #534. Thanks for the contribution!

**Pull request closed without merging**
