### PR TITLE
[WIP] Introduce ValueStringBuilder to improve performance under load

### PR DESCRIPTION
**Pull request by iamcarbon**
Posting for early feedback.

This PR reduces the chance of the StringBuilderPool waiting on a lock or allocating when the project is used in a high-concurrency environment by utilizing a non-allocating ValueStringBuilder (via the .NET runtime).

Seeing a ~4% throughput improvement parsing 32 concurrent documents on an 8 core processor this change. I would also expect we can replace additional uses of StringBuilderPool.Obtain() to improve this further.

This does introduce a dependency on System.Memory, which does complicate things.

## Prerequisites

Please make sure you can check the following two boxes:

- [x] I have read the **CONTRIBUTING** document
- [x] My code follows the code style of this project

## Contribution Type

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [x] All new and existing tests passed

### CODE REVIEW

**Comment by FlorianRappl** [comment]
I love the idea and I think the execution is also great.

My questions now are:

- Does that still work with all supported platforms (build seems to be fine etc.)?
- Are there any performance downsides (e.g., in small-workload scenarios)?
- Since the value string builder is custom (vs the out of the box stringbuilder) what's the anticipated cost of maintenance? Do you think that the standard SB is capable of catching up one day?

All in all it seems to me that there are very little downsides (if any) here. The complexity is higher, but if we are able to save perf. on *any* workload its a definite win.

**Comment by iamcarbon** [comment]
/ Does that still work with all supported platforms (build seems to be fine etc.)?

- Yep, works on all our platform targets.

/ Are there any performance downsides (e.g., in small-workload scenarios)?

- I couldn't spot any regressions in single threaded scenarios, and as long as we're providing reasonable estimates on the default buffer size, should see some notable improvements. We're also able to provide a stack allocated buffer in cases where we're confident in our estimate to improve things further. 

/ Since the value string builder is custom (vs the out of the box stringbuilder) what's the anticipated cost of maintenance? Do you think that the standard SB is capable of catching up one day?

- We cloned directly from the .NET source library and can easily sync up with the changes. ValueStringBuilder is a ref struct over a 3 fields (providing direct access to a continuous buffer) -- I think this is as simple as it gets. StringBuilder has 5 fields and utilizes chunks to grow -- which results in some indirections in data access. Its design likely limits it's ability to be improved much in the future.

**Comment by FlorianRappl** [comment]
Should we merge this or are you planning further enhancements here @iamcarbon ? Thanks! :beers:

**Comment by iamcarbon** [comment]
@FlorianRappl I'm hoping to spend a bit more time benchmarking this and tuning the default buffer sizes before we commit to a merge.

**Comment by iamcarbon** [comment]
Going to revisit thing again with .NET6.0

**Comment by FlorianRappl** [comment]
Thanks for the update!

**Pull request closed without merging**
