### PR TITLE
Release 1.1.1

### PR DESCRIPTION
**Pull request by FlorianRappl**
# Types of Changes

## Prerequisites

Please make sure you can check the following two boxes:

- [x] I have read the **CONTRIBUTING** document
- [x] My code follows the code style of this project

## Contribution Type

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [x] Bug fix (non-breaking change which fixes an issue, please reference the issue id)
- [x] New feature (non-breaking change which adds functionality, make sure to open an associated issue first)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

## Description

New release with some nice fixes and a new addition (`DocumentRequest.PostAsMultipart`).

Thanks to everyone for reporting and contributing!

(We still need to wait for confirmation that the contained fixes help in an issue opened at AngleSharp.Diffing, see https://github.com/AngleSharp/AngleSharp.Diffing/issues/42.)

### CODE REVIEW

**Comment by SebastianStehle** [comment]
Do you have a private nuget repository or do I have to build it myself?

**Comment by SebastianStehle** [comment]
LGTM. Tested it and it works :)

**Comment by FlorianRappl** [comment]
> Do you have a private nuget repository or do I have to build it myself?

It's a preview package that is available on NuGet.

**Comment by SebastianStehle** [comment]
I have tested it by just pulling the repo and adding a project reference.

**Pull request merged**
