### PR TITLE
Better nullability

### PR DESCRIPTION
**Pull request by jodydonetti**
# Types of Changes

## Prerequisites

Please make sure you can check the following two boxes:

- [x] I have read the **CONTRIBUTING** document
- [x] My code follows the code style of this project

## Contribution Type

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [x] Bug fix (non-breaking change which fixes an issue, please reference the issue id)
- [ ] New feature (non-breaking change which adds functionality, make sure to open an associated issue first)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

## Description

Changed a couple of nullability annotations (from `string` to `string?` in the `SetAttribute` method) to better reflect the nullability expectations and how the impl of those methods is internally.

I marked it as a "bug fix" with a non-breaking change, but I don't know if that is correct since this update may generate a warning in other people's code and somebody may have set a stricter configuration which would generate an error.

In case I need to change something let me know.

### CODE REVIEW

**Comment by FlorianRappl** [comment]
No its fine - just need a version change (0.17.2) and a changelog entry. Could you add those?

**Comment by jodydonetti** [comment]
Absolutely, will do asap!

**Comment by jodydonetti** [comment]
Done, I hope everything is fine.

I've set the **release date** in the changelog to today, but probably it should be updated when it will be released.

Thanks!

**Comment by FlorianRappl** [comment]
Yeah that's perfect - thanks a lot! :rocket:

**Pull request merged**
