### PR TITLE
Follow meta refresh (optionally)

### PR DESCRIPTION
**Pull request by georgiosd**
The sanest way I could think to do it :)

### CODE REVIEW

**Comment by FlorianRappl** [comment]
First of all thanks for the nice PR 👍 !

This is not how it should be implemented imho. The design I envision is more flexible and would allow more use cases:

- Bring in a new kind of interface, e.g., `IMetaHandler` specifying a function `void HandleContent(IHtmlMetaElement element)`
- On `SetupElement` the `HtmlMetaElement` looks at the available `IMetaHandler` instances (at the configuration of the contained browsing context)
- It invokes all given handlers (i.e., it is possible that multiple handlers can be applied to the same element / data)
- The refresh handler would now actually set the document's location (potentially after a given time; depending on the content of the meta element)

This approach scales well, as the decision if a refresh should occur is purely done on configuration (via a service). It also allows bringing in own refresh handlers (or wrappers of the default one).

The question now is: Do you also think the one given above is a more suitable design or would you disagree that this is the direction this thing should aim for?

**Comment by georgiosd** [comment]
It's definitely much more configurable, I just don't know if it's an overkill for this.

Personally speaking, it's enough to able to say "I want AngleSharp to respect meta refresh (or not)" but I don't know what that answer is for other people or whether my needs will change over time :)

Sleep on it! I needed this for my own project so I thought I'll send a PR anyway.

**Comment by georgiosd** [comment]
One requirement that does up is: I want to be able to switch on/off this behavior per request.

I've also found that some sites use this meta tag inside `<noscript>` to redirect users to a non-JS page but this is obviously problematic. I think search should be limited to `<head>`

**Comment by FlorianRappl** [comment]
> One requirement that does up is: I want to be able to switch on/off this behavior per request.

That you could implement in such a service. Just also include a callback (configurable) to determine if refresh should be stopped.

> I've also found that some sites use this meta tag inside <noscript> to redirect users to a non-JS page but this is obviously problematic. I think search should be limited to <head>

I am not sure. I think the correct behavior is to ignore noscript (content) in JS mode and to consider it in non-JS mode. As all noscript content is ignored in JS mode the thing with the service would work without extra effort.

**Comment by georgiosd** [comment]
Makes sense! I don't know how you're doing with time but if you start a branch and lay out some of this work, I'll help out.

**Pull request merged**
