### PR TITLE
Issue #442

### PR DESCRIPTION
**Pull request by FlorianRappl**
Renamed the entity services to entity provider (to match the interface name) and unified calls (all end now with semicolons - if available).

### CODE REVIEW

**Comment by corliss** [comment]
Thanks. I am currently on the `master` branch and am going to sync to the `devel` branch. Is it stable, or should I hold off until `devel`is merged into `master`?

**Comment by FlorianRappl** [comment]
It is stable in the sense that `devel` is always building, but API-wise it is not stable. Also since in the upcoming version (v.10.0) CSS is dropped (and I think you care about CSS a lot) you should wait until it is fully released (with the next release also AngleSharp.Css will be published - which gives _at least_ the functionality as it is right now).

**Comment by FlorianRappl** [comment]
(But you could theoretically do a git-cherry-pick to get the specific changes.)

**Comment by corliss** [comment]
Thanks - I will hold off in that case. Are you separating out the CSS assembly? Will it be a separate nuget?

**Comment by FlorianRappl** [comment]
Yes!

**Pull request merged**
